- id: search-and-replace
  name: Search and replace strings
  description: Search and replace strings
  entry: search-and-replace
  language: ruby
  language_version: 3.2
  pass_filenames: true
  exclude_types:
    - binary
